- hosts:
  - wordpress
  # handlers:
  #   - name: "restart apache"
  #     service:

  tasks:
    - name: "Renomar maquina"
      shell: hostname "wordpress" && echo "wordpress" > /etc/hostname
      become: yes # roda como sudo

    - name: "Roda: sudo apt update"
      become: yes # roda como sudo
      apt:
        upgrade: yes
        update_cache: yes

    - name: "Instalar em lote"
      apt:
        name: "{{ item }}"
        state: latest
        with_tems:
          - php7.4
          - apache2
          - libapache2-mod-php7.4
          - php-mysql
          - php-curl
          - mysql-server
          - python3-pycurl
          - python3-mysqldb
          - unzip

    - name: "Fazendo download do wordpress"
      get_url:
        url: "https://br.wordpress.org/lastest-pt_BR.zip"
        dest: "/tmp/lastest-pt_BR.zip"
      
    - name: "Fazendo descompactação do wordpress"
      unarchive:
        src: "/tmp/lastest-pt_BR.zip"
        dest: "/var/www"
        remote_scr: yes
      become: yes

    - name: "Copiar arquivo do wordpress"
      copy:
        src: "/tmp/lastest-pt_BR.zip"
        dest: "/var/www/wordpress/wp-config.php"
        remote_scr: yes
      become: yes

    - name: "configurar senha"
      replace:
        path: "/var/www/wordpress/wp-config.php"
        regexp: "{{ item.value }}"
        repplace: "{{ item.value}}"
      with_items:
        - { regex: 'nome_do_banco_de_dados_aqui', value: 'banco_wordpress' }
        - { regex: 'nome_de_usuario_aqui', value: 'root' }
        - { regex: 'senha_aqui', value: 'root' }
      become: yes

    - name: "Trocando pasta do render do apache para o wordpress"
      copy:
        src: apache/000-default.conf
        dest: "/etc/apache2/sites-available/000-default.conf"
      become: yes
      notify:
        - "restart apache"

    - name: "Lavanta serviço do mysql"
      become: yes
      service:
        name: mysql
        state: started

    - name: "Criando senha root mysql"
      ignore_errors: yes
      become: yes
      mysql_user:
        name: root
        host: localhost
        password: root
        priv: "*.*:ALL,GRANT"
        state: present

    - name: "Cria o banco de dados MySQL"
      mysql_db:
        name: banco_wordpress
        login_user: root
        login_password: root
        state: present
      
    - shell: cat /var/www/wordpress/wp-config.php
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "
# Rodando ansible
# ansible-playbook -i hosts provisionar.yml -u ubuntu --private-key ../../ssh/id_rsa