- hosts:
  - java
  handlers:
    - name: "restart nginx"
      service:
        name: nginx
        state: restarted
      become: yes
  tasks:
    - name: "Renomar maquina"
      shell: hostname "java" && echo "dotnet" > /etc/hostname
      become: yes # roda como sudo

    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    - name: "Instala pacotes"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - nginx
        - default-jdk
        - mysql-server
        - python3-pycurl
        - python3-mysqldb

    - name: "Instalação dotnet"
      shell: "sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-5.0"

    - name: "clone projeto"
      ansible.builtin.git:
        repo: 'https://github.com/torneseumprogramador/spring-web-youtube.git'
        dest: /home/ubuntu/spring-web-youtube
        clone: yes
        update: yes


spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}
spring.datasource.url=jdbc:${DATABASE_URL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show_sql=true
spring.jpa.hibernate.ddl-auto=update

    - name: Adicionar no bashrc
      lineinfile: dest=~/.bashrc line='export API_URL=https://localhost:5001' state=present

      

    - name: Aplicar o bashrc
      shell: source ~/.bashrc
      args:
        executable: /bin/bash

    - name: "fazendo build do projeto"
      shell: "cd mvc_csharp_simples && dotnet build"
    
    - name: "startando VPS"
      shell: "cd mvc_csharp_simples && nohup dotnet run &"

    - name: "Trocando nginx para VPS"
      copy:
        src: "nginx/default"
        dest: "/etc/nginx/sites-available/default"
      become: yes
      notify:
        - "restart nginx"
# Rodando ansible
# ansible-playbook -i hosts provisionar.yml -u ubuntu --private-key ../../ssh/id_rsa