- hosts:
  - java
  handlers:
    - name: "restart nginx"
      service:
        name: nginx
        state: restarted
      become: yes
  tasks:
    - name: "Renomar maquina"
      shell: hostname "java" && echo "dotnet" > /etc/hostname
      become: yes # roda como sudo

    - name: "Roda: sudo apt update"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    - name: "Instala pacotes"
      apt:
        name: "{{ item }}"
        state: latest
      become: yes # roda com sudo
      with_items:
        - nginx
        - default-jdk
        - mysql-server
        - python3-pycurl
        - python3-mysqldb
        - maven

    - name: "Instalação dotnet"
      shell: "sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-5.0"

    - name: "clone projeto"
      ansible.builtin.git:
        repo: 'https://github.com/torneseumprogramador/spring-web-youtube.git'
        dest: /home/ubuntu/spring-web-youtube
        clone: yes
        update: yes

    - name: Adicionar no bashrc
      lineinfile: dest=~/.bashrc line='export USER=root' state=present

    - name: Adicionar no bashrc
      lineinfile: dest=~/.bashrc line='export PASSWORD=root' state=present

    - name: Adicionar no bashrc
      lineinfile: dest=~/.bashrc line='export DATABASE_URL='mysql://localhost:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC' state=present  

    - name: Aplicar o bashrc
      shell: source ~/.bashrc
      args:
        executable: /bin/bash

    - name: "fazendo build do projeto"
      shell: "cd spring-web-youtube && mvn package"
    
    - name: "startando VPS"
      shell: "cd spring-web-youtube && nohup java -jar &"

    - name: "Trocando nginx para VPS"
      copy:
        src: "nginx/default"
        dest: "/etc/nginx/sites-available/default"
      become: yes
      notify:
        - "restart nginx"
# Rodando ansible
# ansible-playbook -i hosts provisionar.yml -u ubuntu --private-key ../../ssh/id_rsa